USE customer_analysis;
#Q1. Total revenue generated by male vs female customers
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY gender;
#Q2. Customers who used discounts but spent more than average purchase amount
SELECT 
    customer_id,
    purchase_amount
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM shopping_data
);
USE customer_analysis;
SELECT * FROM shopping_data LIMIT 5;
#Q2. Customers who used discounts but spent more than average purchase amount
SELECT 
    customer_id,
    purchase_amount
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM shopping_data
);
#Q3. Top 5 products with highest average review rating
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
#Q4. Average purchase amount between Standard and Express Shipping
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
#why output not showing

#Q2. Customers who used discounts but spent more than average purchase amount
SELECT 
    customer_id,
    purchase_amount
FROM shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM shopping_data
);
#Q3. Top 5 products with highest average review rating
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
#Q4. Average purchase amount between Standard and Express Shipping
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
#Q5. Compare subscriber vs non-subscriber spending
SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY subscription_status;
#6 Top 5 products with highest discount percentage
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS discount_percentage
FROM shopping_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
#Q7. Customer segmentation based on previous purchases
SELECT 
    CASE
        WHEN previous_purchases BETWEEN 0 AND 2 THEN 'New'
        WHEN previous_purchases BETWEEN 3 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM shopping_data
GROUP BY customer_segment;
#8Q8. Top 3 most purchased products within each category
WITH product_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        RANK() OVER(
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM shopping_data
    GROUP BY category, item_purchased
)

SELECT *
FROM product_count
WHERE rank_num <= 3;
#9Q9. Are repeat buyers more likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;
#10 Revenue contribution of each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;